### ISSUE TITLE
Incompatibility with concourse 4.0

### ISSUE THREAD

**Issue by edwardecook** [albertoleal/concourse-flake-hunter#5]
Since we bumped to concourse 4.0 we have been seeing the following error as part of the `hunt` task:
```
/tmp/build/8c72b58e/go/src/github.com/albertoleal/concourse-flake-hunter /tmp/build/8c72b58e
failed to authenticate to team: resource not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6d8bc7]

goroutine 5 [running]:
github.com/albertoleal/concourse-flake-hunter/hunter.(*Searcher).getBuildsFromPage(0xc420046f10, 0xc420064780, 0x0, 0x0, 0x12c, 0xc42009d5e0, 0xc4200b2c00)
	/tmp/build/8c72b58e/go/src/github.com/albertoleal/concourse-flake-hunter/hunter/searcher.go:58 +0xc7
created by github.com/albertoleal/concourse-flake-hunter/hunter.(*Searcher).Search
	/tmp/build/8c72b58e/go/src/github.com/albertoleal/concourse-flake-hunter/hunter/searcher.go:42 +0x8f
```
It looks to us as though this is due to the change in the team struct from concourse-go.

We have started to look at solving this by bumping the vendored versions of concourse/atc and concourse/go-concourse but fixing concourse-flake-hunter to make use of the new structs due to changes such as https://github.com/concourse/go-concourse/commit/df59e8a20328c506be9be1870e5501c4fb33b15a#diff-90620ae1fcf1dc42250a9bbe642a98b8

**Comment by albertoleal** [comment]
Hi @edwardecook thanks for that. Please let me know how it goes and if I can help with anything.
